name: Update Images JSON

on:
  push:
    paths:
      - 'Images/**'

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate images.json
        run: |
          # Lister toutes les images dans le dossier 'images'
          find Images/ -type f -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' -o -name '*.gif' > images.txt
          # Créer un fichier JSON avec la liste des images
          echo '[' > images.json
          while read -r image; do
            echo "  \"${image}\"," >> images.json
          done < images.txt
          # Retirer la dernière virgule
          sed -i '$ s/,$//' images.json
          echo ']' >> images.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add images.json
          git commit -m "Update images.json"
          git push
