name: Update Images JSON

on:
  push:
    paths:
      - 'Images/**'

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate images.json
        run: |
          find Images/ -type f -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' -o -name '*.gif' > images.txt
          echo '[' > images.json
          while read -r image; do
            echo "  \"${image}\"," >> images.json
          done < images.txt
          sed -i '$ s/,$//' images.json
          echo ']' >> images.json

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add images.json
          git commit -m "Update images.json"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
