name: Update Images JSON

on:
  push:
    paths:
      - '.github/workflows/**'  # Déclenche l'action quand un fichier de workflow est modifié
      - 'Images/**'  # Ajouter ici d'autres chemins qui doivent déclencher l'action
  pull_request:
    paths:
      - '.github/workflows/**'  # Déclenche l'action quand un fichier de workflow est modifié
      - 'Images/**'  # Ajouter ici d'autres chemins

permissions:
  contents: write  # Ajoute cette ligne pour permettre l'écriture dans le dépôt

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate images.json
        run: |
          find Images/ -type f -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' -o -name '*.gif' > images.txt
          echo '[' > images.json
          while read -r image; do
            echo "  \"${image}\"," >> images.json
          done < images.txt
          sed -i '$ s/,$//' images.json
          echo ']' >> images.json

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add images.json
          git commit -m "Update images.json"
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
